<?php

use Drupal\localgov_core\FieldRenameHelper;

/**
 * Update Field storage for core fields email_address, facebook, phone, twitter.
 */
function localgov_core_update_8001(&$sandbox) {

  // Update field_ types fields provided by localgov_core.
  $field_names = ['email_address', 'facebook', 'phone', 'twitter'];
  foreach ($field_names as $field_name_unprefixed) {
    FieldRenameHelper::renameField('field_' . $field_name_unprefixed, 'localgov_' . $field_name_unprefixed, 'node');
  }
}
